services:
  projector-manager:
    build: .
    container_name: projector-manager
    restart: unless-stopped
    environment:
      - PROJECTOR_IP=192.168.1.228
      - PORT=3005
    network_mode: host
